site_name: yumo
repo_url: https://github.com/luocfprime/yumo
site_url: https://luocfprime.github.io/yumo
site_description: Scalar field visualization using Polyscope.
site_author: Chaofan Luo
edit_uri: edit/main/docs/
copyright: Maintained by <a href="https://github.com/luocfprime">luocfprime</a>.

nav:
  - Home: index.md
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [
            "yumo"
            ]
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/luocfprime/yumo
  alternate:
    - name: English
      link: en/
      lang: en
    - name: Chinese
      link: zh/
      lang: zh

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
