site_name: yumo
repo_url: https://github.com/luocfprime/yumo
site_url: https://luocfprime.github.io/yumo
site_description: Scalar field visualization using Polyscope.
site_author: Chaofan Luo
edit_uri: edit/main/docs/
copyright: Maintained by <a href="https://github.com/luocfprime">luocfprime</a>.

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Modules: modules.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [
            "yumo"
            ]
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
  - macros:
      j2_variable_start_string: '[['
      j2_variable_end_string: ']]'

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/luocfprime/yumo
  alternate:
    - name: English
      link: en
      lang: en
    - name: Chinese
      link: zh/
      lang: zh
  url:
    prefix: '.'
    videos: '/yumo'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: underscore
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
